name: Build Test APK
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install base deps
        run: npm install --legacy-peer-deps
      - name: Install AdMob for Capacitor 5
        run: npm install @capacitor-community/admob@5 --save --legacy-peer-deps
      - name: Build web
        run: npm run build
      - name: Sync Capacitor
        run: npx cap sync android
      - name: Build signed APK
        working-directory: android
        run: |
         ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=../upload-keystore.jks \
            -Pandroid.injected.signing.store.password=Uhk@738_ghRU87@98dfs \
            -Pandroid.injected.signing.key.alias=upload \
            -Pandroid.injected.signing.key.password=Uhk@738_ghRU87@98dfs
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed-apk
          path: android/app/build/outputs/apk/release/app-release.apk
